services:
  app:
    image: nginx:alpine
    container_name: ghs_rechnungsmanager
    restart: always
    ports:
      - "8080:80" # Geändert von 80:80 auf 8080:80, da Port 80 bereits belegt ist
    volumes:
      - .:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
